package com.moneymate.backend.controller;

import java.io.ByteArrayInputStream;
import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.moneymate.backend.dto.IncomeDTO;
import com.moneymate.backend.entity.ProfileEntity;
import com.moneymate.backend.service.EmailService;
import com.moneymate.backend.service.ExcelExportService;
import com.moneymate.backend.service.IncomeService;
import com.moneymate.backend.service.ProfileService;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@RestController
@RequestMapping("/email")
public class EmailExcelController {
    private final ProfileService profileService;
    private final EmailService emailService;
    private final IncomeService incomeService;
    private final ExcelExportService excelExportService;

    @GetMapping("/income-excel")
    public ResponseEntity<String> emailIncomeExcel() {
    // 1. Get the current user's profile to find their email address
    ProfileEntity profile = profileService.getCurrentProfile();

    String userEmail = profile.getEmail();

    // 2. Fetch the data
    List<IncomeDTO> incomes = incomeService.getCurrentMonthExpensesForCurrentProfile();

    // 3. Generate the Excel file in memory
    ByteArrayInputStream in = excelExportService.exportIncomesToExcel(incomes);

    // Convert the InputStream to a byte array so we can attach it
    byte[] excelBytes = in.readAllBytes();

    // 4. Prepare the email content
    String subject = "Your Income Details - moneyMate";
    String body = "Hello " + profile.getFullName() + " ,<br>Please find attached your requested income tracking details generated by moneyMate.<br>Keep up the great work tracking your finances!<br><br>Best regards,<br>The moneyMate Team";

    // 5. Send it!
    emailService.sendEmailWithAttachment (userEmail, subject, body, excelBytes, 

"income_details.xlsx");

        // Return a simple success message to your React toast notification
        return ResponseEntity.ok("Email sent successfully");
    }
}
